name: my first workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: welcome-message
              run: echo "my first github actions job"

            - name: list of files
              run: ls

            - name: read file
              run: cat README.md
              